- hosts:  all
  become: yes

  roles:
     - role: ansiblebit.oracle-java
       oracle_java_set_as_default: yes
       oracle_java_version: 8

     - role: geerlingguy.docker

     - role: shelleg.gradle
       gradle_version_major: "2"
       gradle_version_minor: "7"

  tasks:

    - name: add osxcross
      apt_repository:
        repo: ppa:hogliux/osxcross
        codename: trusty

    - name: add golang ppa
      apt_repository:
        repo: ppa:longsleep/golang-backports

    - name: update cache
      shell: apt-get update

    - name: install packages
      apt:
        install_recommends: no
        name: "{{ item }}"
      with_items:
        - nsis
        - libffi-dev
        - ant
        - awscli
        - postgresql-client
        - mysql-client
        - golang-1.8
        - xar
        - bomutils
        - libssl-dev
        - libxml2-dev
        - cpio

    - name: configure golang
      shell: ln -s /usr/lib/go-1.8/ /usr/local/go

    - name: Install pip packages
      pip:
        name:
          - dox
          - twine
          - pynsist
          - wheel
          - tox
          - mcommons

    - shell: "CFLAGS=-I/usr/include/libffi/include pip install pyOpenSSL paramiko cryptography>=1.1"

    - name: install security policies
      action: copy src=files/local_policy.jar dest=/usr/lib/jvm/java-8-oracle/jre/lib/security/

    - name: install security policies
      action: copy src=files/US_export_policy.jar dest=/usr/lib/jvm/java-8-oracle/jre/lib/security/

    - name: install nodejs
      shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && apt-get install -y nodejs

    - name: Install node.js packages globally
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - node-gyp
        - webdriver-manager
        - gulp
        - rollup
        - bower
        - node-sass
        - karma
        - yarn

    - name: Cleanup
      shell: apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && find /var/cache -type f -exec rm -rf {} \;