- hosts:  all
  become: yes
  tasks:

    - name: update cache
      shell: apt-get update

    - name: install packages
      apt:
        install_recommends: no
        name: "{{ item }}"
      with_items:
        - nsis
        - nodejs

    - name: Install pip packages
      pip:
        name:
          - papertrail-cli

    - name: Install node.js packages globally
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - node-gyp
        - webdriver-manager
        - selenium-standalone
        - gulp
        - rollup
        - bower
        - node-sass
        - karma
        - yarn@0.27.5
        - webdriverio

    - name: update webdriver-manager
      shell: webdriver-manager update

    - shell: selenium-standalone install
