- hosts:  all
  become: yes

  roles:
     - role: cmprescott.chrome
     - role: rdeknijf.chromedriver
     - role: geerlingguy.docker

  tasks:

    - name: update cache
      shell: apt-get update

    - name: install packages
      apt:
        install_recommends: no
        name: "{{ item }}"
      with_items:
        - nsis
        - nodejs

    - name: Install pip packages
      pip:
        name:
          - papertrail-cli

    - name: install security policies
      action: copy src=files/local_policy.jar dest=/usr/lib/jvm/java-8-oracle/jre/lib/security/

    - name: install security policies
      action: copy src=files/US_export_policy.jar dest=/usr/lib/jvm/java-8-oracle/jre/lib/security/

    - name: Install node.js packages globally
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - node-gyp
        - webdriver-manager
        - selenium-standalone
        - gulp
        - rollup
        - bower
        - node-sass
        - karma
        - yarn
        - webdriverio

    - name: update webdriver-manager
      shell: webdriver-manager update

    - shell: selenium-standalone install

    - name: install gradle
      unarchive:
        src: https://services.gradle.org/distributions/gradle-2.7-bin.zip
        mode: a+x
        creates: /usr/local/gradle-2.7
        remote_src: yes
        dest: /usr/local/

    - name: install micro
      unarchive:
        src: https://github.com/zyedidia/micro/releases/download/v1.3.3/micro-1.3.3-linux64.tar.gz
        mode: a+x
        creates: /usr/local/bin/micro
        dest: /usr/local
        remote_src: yes

    - name: install ant
      unarchive:
        src: http://www-eu.apache.org/dist//ant/binaries/apache-ant-1.9.9-bin.zip
        dest: /usr/local
        remote_src: yes

    - name: add ant to path
      file:
        src:  /usr/local/apache-ant-1.9.9/bin/ant
        dest: /usr/local/bin/ant
        state: link

    - name: add gradle to path
      file:
        src:  /usr/local/gradle-2.7/bin/gradle
        dest: /usr/local/bin/gradle
        state: link

    - name: Cleanup
      shell: apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && find /var/cache -type f -exec rm -rf {} \;