- hosts:  all
  become: yes
  tasks:

    - name: "add apt keys"
      apt_key: url="{{item}}" state=present
      with_items:
        - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - https://dl-ssl.google.com/linux/linux_signing_key.pub
        - https://download.docker.com/linux/ubuntu/gpg
        - http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xC2518248EEA14886

    - name: install roles
      shell:  "ansible-galaxy install {{item}}"
      with_items:
        - geerlingguy.docker
        - rdeknijf.chromedriver
        - cmprescott.chrome
        - Moshe-Immerman.javatools

    - name: update cache
      shell: apt-get update

    - name: install packages
      apt:
        install_recommends: no
        name: "{{ item }}"
      with_items:
        - nsis
        - libffi-dev
        - awscli
        - postgresql-client
        - mysql-client
        - libssl-dev
        - libxml2-dev
        - cpio
        - xvfb
        - tinywm

    - name: Install pip packages
      pip:
        name:
          - dox
          - twine
          - pynsist
          - wheel
          - tox
          - mcommons
          - papertrail-cli

    - name: add repos
      apt_repository:
        repo: "{{item}}"
        state: present
      with_items:
        - deb https://deb.nodesource.com/node_7.x xenial main
        - deb-src https://deb.nodesource.com/node_7.x xenial main

    - name: Cleanup
      shell: apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && find /var/cache -type f -exec rm -rf {} \;